import '../model/food_model.dart';

List<FoodModel> FOODLIST = <FoodModel>[
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
  FoodModel(
      "Burger",
      "KFC",
      "https://d2nzqyyfd6k6c7.cloudfront.net/styles/nova_evo_landscape/s3/article/thumbnail/kfc_australia_ig_0.jpg?itok=0mD6_Ecw",
      2.99),
];
